import 'package:uni_absence/features/AttendanceRecords/data/student_attendance_model.dart';

final List<StudentAttendanceModel> studentsList = [
  StudentAttendanceModel(
    id: "221236",
    level: "4",
    department: "is",
    name: "Abdallah Ramadan Othman ",
    attendTime: "09:00 AM",
    leaveTime: null,
    attended: true,
    left: false,
  ),
  StudentAttendanceModel(
    id: "220102",
    level: "4",
    department: "CS",
    name: "Mohamed Ali ",
    attendTime: "09:05 AM",
    leaveTime: "11:30 AM",
    attended: true,
    left: true,
  ),
  StudentAttendanceModel(
    id: "220103",
    level: "3",
    department: "IS",
    name: "Omar Hassan",
    attendTime: "09:10 AM",
    leaveTime: null,
    attended: false,
    left: false,
  ),
  StudentAttendanceModel(
    id: "220104",
    level: "2",
    department: "AI",
    name: "Youssef Ahmed",
    attendTime: "09:15 AM",
    leaveTime: "12:00 PM",
    attended: true,
    left: true,
  ),
  StudentAttendanceModel(
    id: "220105",
    level: "1",
    department: "SE",
    name: "Sara Mohamed",
    attendTime: "09:20 AM",
    leaveTime: null,
    attended: false,
    left: false,
  ),
  StudentAttendanceModel(
    id: "220106",
    level: "4",
    department: "IT",
    name: "Ali Hassan",
    attendTime: "09:25 AM",
    leaveTime: "11:45 AM",
    attended: true,
    left: true,
  ),

  StudentAttendanceModel(
    id: "220107",
    level: "3",
    department: "CS",
    name: "Mona Ahmed",
    attendTime: "09:30 AM",
    leaveTime: null,
    attended: false,
    left: false,
  ),
  StudentAttendanceModel(
    id: "220108",
    level: "2",
    department: "IS",
    name: "Hassan Mohamed",
    attendTime: "09:35 AM",
    leaveTime: "12:15 PM",
    attended: true,
    left: true,
  ),
  StudentAttendanceModel(
    id: "220109",
    level: "1",
    department: "AI",
    name: "Fatma Ali",
    attendTime: "09:40 AM",
    leaveTime: null,
    attended: false,
    left: false,
  ),
  StudentAttendanceModel(
    id: "220110",
    level: "4",
    department: "SE",
    name: "Ahmed Hassan",
    attendTime: "09:45 AM",
    leaveTime: "11:50 AM",
    attended: true,
    left: true,
  ),

  StudentAttendanceModel(
    id: "220111",
    level: "3",
    department: "IT",
    name: "Laila Mohamed",
    attendTime: "09:50 AM",
    leaveTime: null,
    attended: false,
    left: false,
  ),
];
